# Generated by Django 3.1.4 on 2020-12-13 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600)),
                ('content', models.TextField()),
                ('image_one', models.ImageField(upload_to='blog/<django.db.models.fields.CharField>')),
                ('image_two', models.ImageField(upload_to='blog/<django.db.models.fields.CharField>')),
                ('image_three', models.ImageField(upload_to='blog/<django.db.models.fields.CharField>')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.categorie')),
            ],
        ),
    ]
