# Generated by Django 3.1.4 on 2020-12-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_one',
            field=models.ImageField(null=True, upload_to='blog/<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_three',
            field=models.ImageField(null=True, upload_to='blog/<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_two',
            field=models.ImageField(null=True, upload_to='blog/<django.db.models.fields.CharField>'),
        ),
    ]
