# Generated by Django 3.1.4 on 2020-12-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201213_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
