# Generated by Django 3.0.8 on 2021-01-06 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_special'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorie',
            new_name='Designs3D',
        ),
        migrations.RenameModel(
            old_name='Special',
            new_name='Vastu',
        ),
    ]
